### ISSUE TITLE
update data command for aiida 0.11.0

### ISSUE THREAD

**Issue by ltalirz** [albgar/aiida_siesta_plugin#13]
Installing aiida-siesta 0.9.8 together with  aiida 0.11.0 breaks the `verdi data` command:

```
$ verdi data
Traceback (most recent call last):
  File "/home/max/.virtualenvs/aiida/bin/verdi", line 11, in <module>
    sys.exit(run())
  File "/home/max/.virtualenvs/aiida/local/lib/python2.7/site-packages/aiida/cmdline/verdilib.py", line 1049, in run
    aiida.cmdline.verdilib.exec_from_cmdline(sys.argv)
  File "/home/max/.virtualenvs/aiida/local/lib/python2.7/site-packages/aiida/cmdline/verdilib.py", line 1033, in exec_from_cmdline
    CommandClass = list_commands[command]()
  File "/home/max/.virtualenvs/aiida/local/lib/python2.7/site-packages/aiida/cmdline/commands/data.py", line 52, in __init__
    self.routed_subcommands[cmd.name] = verdi
AttributeError: type object '_Psf' has no attribute 'name'
```
This is currently blocking a release of Quantum Mobile with aiida 0.11.0

See also aiidateam/aiida_core#1104

**Comment by albgar** [comment]
Hi,
We have recently updated the aiida-siesta package to use the new 'command' plugin framework. The update is not yet in PyPi (working on this), but it is tagged as 0.11.5 in the albgar/aiida_siesta_plugin GitHub project.

**Comment by ltalirz** [comment]
Cool!
I'm not sure I'll find the time to do another release before later this week, let me know when available on PyPI

**Comment by vdikan** [comment]
Hello!
`aiida-siesta 0.11.5` should be available now on PyPI.

**Comment by ltalirz** [comment]
new Quantum Mobile release is out :-)
https://github.com/marvel-nccr/quantum-mobile/releases
